### ISSUE TITLE
Andere Delegation freigeben

### ISSUE THREAD

**Issue by maximilianilzhoefer** [PeerConradi/munity#10]
Es ist derzeit möglich, dass ich eine Application einrichte in der ich gar nicht Mitglied bin. 
![image](https://user-images.githubusercontent.com/55856340/141815446-fccb1ae1-9b2a-43be-b10a-db9273278ffa.png)
![image](https://user-images.githubusercontent.com/55856340/141815504-446ba850-aa5e-44fd-a94c-57343b30fd31.png)

**Comment by PeerConradi** [comment]
Should be fixed in version 1.0.5.2
