### ISSUE TITLE
Hängt sich auf wenn man Antrag annimmt

### ISSUE THREAD

**Issue by dvdkblk** [PeerConradi/munity#49]
Beim Annehmen eines Änderungsantrags bleibt die Ansicht hängen und das Feld annehmen kann nicht weggeklickt werden. Auch wenn es im Hintergrund noch zu laufen scheint. Neu laden behebt das Problem nicht

**Comment by PeerConradi** [comment]
Der Arbeitsablauf zum Annehmen ist durch die Hervorheben Funktion jetzt etwas umgestalltet. Bitte hiermit testen

**Comment by dvdkblk** [comment]
Sieht gut aus :)
