### ISSUE TITLE
live demo does not work, agenda folder, approvals

### ISSUE THREAD

**Issue by weedkiller** [PeerConradi/munity#5]
Hello this link doesnt work https://www.mun-tools.com/

great work btw. 👍🏾 

- [ ] is there an ability to vote and create a meeting minutes folder
- [ ] is there an approval flow we can use with this for eg. users or manager needs to approve new agendas etc.

**Comment by m1212e** [comment]
Hi,

could you elaborate a bit more on those two things?
I'ts unclear what you mean by "meeting minutes folder".
Regarding the second question, do you mean a check or restriction which should prevent uncontrolled creation of new agendas?
Maybe if you could tell us about that workflow you mentioned we can provide more information.

Thank you for your interest in the project

**Comment by weedkiller** [comment]
hi thanks for taking the time to respond.

Voting-Agenda-Folder/Dockett, For e.g. if there were a board meeting held - this typically produces  votes, agenda items, issues etc. Collectively it would nice to gather that as a folder item corresponding to that meeting so that it could be tracked or revisited later.

This collection could be a dynamicobject or composite object that holds those items


In reference to the second item, often agenda items or issues discussed would be taken up as _follow up action items_ to be resolved. When they are resolved by one of the community members, then it would be routed for approval to a board member or someone else who would verify and approve it.
