### ISSUE TITLE
Extra-Feature: Farben bei Abstimmungen

### ISSUE THREAD

**Issue by dvdkblk** [PeerConradi/munity#55]
Richtig hübsch wäre es wenn in dem Tortendiagramm die Pro-Stimmen grün, contra rot und Enthaltungen gelb sind

**Comment by PeerConradi** [comment]
Derzeit nicht möglich siehe: https://blazor.radzen.com/styling-chart

**Comment by dvdkblk** [comment]
Jo dann ist's egal 😄
