### ISSUE TITLE
Zuordnung der Nichstaatlichen Akteure

### ISSUE THREAD

**Issue by dvdkblk** [PeerConradi/munity#59]
Ein paar Nichstaatliche Akteure sind irgendwie falsch den Gremien zugeordnet. Korrekt ist: 

- GV: Human rights watch, World economic forum
- HA3: UN Women, Save the children
- MRR: Reporter ohne Grenzen, Amnesty International
- SR Welthungerhilfe

**Comment by PeerConradi** [comment]
Hab ich mal angepasst. Bitte die Liste der Staaten und NAs noch einmal kontrollieren

**Comment by dvdkblk** [comment]
Super! Einziges was fehlt ist die Welthungerhilfe im Sicherheitsrat
