### ISSUE TITLE
Typo: Änderungsantrag im Resolutionseditor

### ISSUE THREAD

**Issue by dvdkblk** [PeerConradi/munity#63]
Antrag auf St**r**eichung

**Comment by dvdkblk** [comment]
Ich nutze es mal als Sammlung von Typos. (Alles halb so wild, nur damit du die weißt)
- Neue**s** Abstimmung
- Präamb**el**

**Comment by PeerConradi** [comment]
Präambel finde ich nicht wo es falsch ist. Für Typos bitte immer sagen wo die falsch sind
